export const transactionMessages: Record<string, string> = {
  '00': 'Your transaction was approved! Thank you for your payment.',
  '01': 'Please contact your financial institution for further assistance.',
  '02': 'Your transaction needs special conditions. Please refer to your financial institution.',
  '03': 'There was an issue with the merchant. Please try again later.',
  '04': 'Your card needs to be picked up. Please check with your bank.',
  '05': 'Transaction declined. Please contact your bank for more details.',
  '06': 'An error occurred. Please try again later.',
  '07': 'Your card needs to be picked up due to special conditions.',
  '08': 'Please provide identification at your bank for this transaction.',
  '09': 'Your transaction is still in progress. Please wait.',
  '10': 'Transaction approved by your financial institution.',
  '11': 'Transaction approved by your financial institution.',
  '12': 'The transaction is invalid. Please check your details.',
  '13': 'The amount entered is incorrect. Please verify and try again.',
  '14': 'Invalid card number. Please check your card details.',
  '15': 'No such financial institution found. Please check with your bank.',
  '16': 'Transaction approved with additional track update. Check with your bank.',
  '17': 'Transaction canceled by customer.',
  '18': 'Customer dispute occurred. Please contact your bank.',
  '19': 'Please re-enter your transaction.',
  '20': 'Invalid response from the financial institution. Please try again.',
  '21': 'No action taken by the financial institution.',
  '22': 'Suspected malfunction. Please try again later.',
  '23': 'Unacceptable transaction fee.',
  '24': 'File update not supported. Please try again later.',
  '25': 'Record not found. Please verify the details and try again.',
  '26': 'Duplicate record. Please check your transaction details.',
  '27': 'Error in file update. Please contact support.',
  '28': 'File is locked for update. Please try again later.',
  '29': 'File update failed. Please try again later.',
  '30': 'Format error. Please check your details and try again.',
  '31': 'Your bank is not supported. Please contact your bank.',
  '32': 'Transaction partially completed. Please contact support.',
  '33': 'Your card has expired. Please check with your bank.',
  '34': 'Suspected fraud. Your card has been picked up.',
  '35': 'Contact your bank. Card picked up.',
  '36': 'Your card is restricted. Please contact your bank.',
  '37': 'Call your bank for security. Card picked up.',
  '38': 'Too many incorrect PIN attempts. Your card is locked.',
  '39': 'No credit account found. Please contact your bank.',
  '40': 'Function not supported by your card.',
  '41': 'Lost card. Please contact your bank.',
  '42': 'No universal account found. Please contact your bank.',
  '43': 'Stolen card. Contact your bank immediately.',
  '44': 'No investment account found. Please verify your details.',
  '51': 'Insufficient funds in your account. Please try again later.',
  '52': 'No check account found. Please contact your bank.',
  '53': 'No savings account found. Please contact your bank.',
  '54': 'Your card has expired. Please update your card details.',
  '55': 'Incorrect PIN entered. Please try again.',
  '56': 'No card record found. Please check your details.',
  '57': 'Transaction not permitted on your card.',
  '58': 'Transaction not permitted on this terminal.',
  '59': 'Suspected fraud. Please contact your bank.',
  '60': 'Contact your bank for further assistance.',
  '61': 'Withdrawal limit exceeded. Please try a lower amount.',
  '62': 'Restricted card. Please contact your bank.',
  '63': 'Security violation detected. Please contact your bank.',
  '64': 'Original amount is incorrect. Please check your transaction details.',
  '65': 'Withdrawal frequency exceeded. Please try again later.',
  '66': 'Call your bank security for verification.',
  '67': 'Card capture error. Please contact your bank.',
  '68': 'Response received too late. Please try again later.',
  '75': 'PIN attempts exceeded. Your card has been locked.',
  '90': 'Transaction cut-off in progress. Please try again later.',
  '91': 'Issuer or switch inoperative. Please try again later.',
  '92': 'Routing error. Please contact your bank.',
  '93': 'Transaction violation. Please check your details.',
  '94': 'Duplicate transaction detected. Please verify your transaction.',
  '95': 'Reconcile error. Please contact support.',
  '96': 'System malfunction. Please try again later.',
  '98': 'Cash limit exceeded. Please contact your bank.',
  'Z0': 'Transaction not completed. Please try again.',
  'Z4': 'Integration error. Please contact support.',
  'Z1': 'Transaction error. Please contact support.',
  'Z1(46)': 'Wrong login details. Please check your credentials.',
  'Z5': 'Duplicate transaction reference. Please try again later.',
  'Z6': 'Customer cancellation.',
  'Z25': 'Transaction not found. Please verify your transaction details.',
  'Z30': 'Cannot retrieve risk profile. Please contact support.',
  'Z61': 'Payment requires token. Please check your payment details.',
  'Z62': 'Token request was successful.',
  'Z63': 'Token not generated. Customer not registered.',
  'Z64': 'Error generating token. Please try again.',
  'Z65': 'Payment requires token authorization. Please verify.',
  'Z66': 'Token authorization successful.',
  'Z67': 'Token authorization failed. Incorrect token.',
  'Z68': 'Error authenticating token. Please try again.',
  'Z69': 'Customer cancellation on secure 3D.',
  'Z70': 'Cardinal authentication required. Please verify.',
  'Z71': 'Cardinal lookup successful.',
  'Z72': 'Cardinal lookup failed. Card does not exist.',
  'Z73': 'Cardinal authentication successful.',
  'Z74': 'Cardinal authentication failed. Please try again.',
  'Z8': 'Invalid card details. Please check your card.',
  'Z81': 'Bin not configured. Please contact support.',
  'Z82': 'Merchant not configured for bin. Please contact support.',
  'Z9': 'Cannot connect to passport service. Please try again.',
  'A3': 'Database error. Please contact support.',
  'A9': 'Incorrect phone number. Please verify.',
  'X04': 'Minimum payment amount not met. Please check.',
  'X03': 'Exceeds maximum allowed amount. Please verify.',
  'X10': '3D Secure authentication failed.',
  'T0': 'Token request successful.',
  'T1': 'Token request failed. Please verify your details.',
  'T2': 'Token authentication pending.',
  'S0': 'Timeout calling postilion service. Please try again.',
  'S1': 'Invalid response from postilion service.',
  'XG0': 'Cannot retrieve collections account.',
  'XG1': 'Successfully retrieved collections account.',
  'XG2': 'Could not retrieve collections account.',
  'PC1': 'Could not retrieve prepaid card number.',
  'XS1': 'Exceeded time period to complete transaction.',
  'XNA': 'No acquirer found.',
  'AE1': 'Auto enrollment balance enquiry failed.',
  'AE2': 'Auto enrollment account and phone validation failed.',
  'AE3': 'Auto enrollment cannot add card to safe token.',
  'AE4': 'Auto enrollment error occurred.',
  'E10': 'Missing service identifier.',
  'E11': 'Missing transaction type.',
  'E12': 'Missing authentication credentials.',
  'E18': 'Service provider unreachable.',
  'E19': 'Invalid response received.',
  'E20': 'Request timed out.',
  'E21': 'Unknown error occurred.',
  'E34': 'System busy. Please try again later.',
  'E42': 'Invalid authentication data.',
  'E43': 'PIN cannot be empty.',
  'E48': 'Invalid OTP identifier code.',
  'E49': 'Invalid authentication data version.',
  'E54': 'Could not get response from HSM.',
  'E56': 'Invalid character in PAN.',
  'E57': 'Invalid character in PIN.',
  'E60': 'Invalid merchant code.',
  'E61': 'Invalid payable code.',
  '20021': 'No hash found.',
  '20031': 'Invalid value for ProductId.',
  '20050': 'Wrong hash computation.',
};

export const WEB_PAY_HOST_DEV = 'https://isw-inline-checkout-webview.k8.isw.la';

export const WEB_PAY_HOST_PROD =
  'https://isw-inline-checkout-webview.k8.isw.la';

export const SITE_REDIRECT_URL = 'https://blank.org';
